---

driver                      :
    name                    : docker
    socket                  : unix:///var/run/docker.sock
    use_sudo                : false
    privileged              : true
    volume                  : /opt/concourseci/worker
    provision_command       : mkdir -p /run/sshd

verifier                    :
  name                      : serverspec
  remote_exec               : false
  default_pattern           : true
  bundler_path              : <%= '/opt/hellofresh/kitchen/embedded/bin' if File.exist?('/opt/hellofresh/kitchen/embedded/bin/bundler') %>
  rspec_path                : <%= '/opt/hellofresh/kitchen/embedded/bin' if File.exist?('/opt/hellofresh/kitchen/embedded/bin/rspec') %>
  gemfile                   : ./test/integration/Gemfile

provisioner                 :
    name                    : ansible_push
    ansible_config          : "tests/ansible.cfg"
    chef_bootstrap_url      : nil
    use_instance_name       : True
    idempotency_test        : True
    diff                    : True
    sudo                    : True
    extra_vars              : "@./test/integration/simple/concourse-vars.yml"
    raw_arguments           : "-e concourseci_version=<%= ENV['concourseci_version'] || 'v7.0.0' %> --extra-vars='ansible_python_interpreter=/usr/bin/python3'"
    # verbose                 : "vvvvv"

platforms                   :
### Ubuntu 1804
 - name                     : "ubuntu1804"
   driver_config            :
     image                  : ubuntu:18.04
     platform               : ubuntu
   provisioner              :
      groups                :
         concourse-web      :
                              - 'simple-ubuntu1804'
         concourse-worker   :
                              - 'simple-ubuntu1804'
                              - 'worker-ubuntu1804'
# ## Ubuntu 2004
#  - name                     : "ubuntu2004"
#    driver_config            :
#      image                  : ubuntu:20.04
#      platform               : ubuntu
#    provisioner              :
#       groups                :
#          concourse-web      :
#                               - 'simple-ubuntu2004'
#          concourse-worker   :
#                               - 'simple-ubuntu2004'
#                               - 'worker-ubuntu2004'
suites:
  - name                    : simple
    provisioner             :
      playbook              : "test/integration/simple/simple.yml"
    driver_config           :
      hostname              : "simple"
