---

driver                      :
    name                    : docker
    socket                  : unix:///var/run/docker.sock
    use_sudo                : false
    privileged              : true
    volume                  : /opt/concourseci/worker
    provision_command       : mkdir -p /run/sshd

verifier                    :
  name                      : serverspec
  remote_exec               : false
  default_pattern           : true
  bundler_path              : <%= '/opt/hellofresh/kitchen/embedded/bin' if File.exist?('/opt/hellofresh/kitchen/embedded/bin/bundler') %>
  rspec_path                : <%= '/opt/hellofresh/kitchen/embedded/bin' if File.exist?('/opt/hellofresh/kitchen/embedded/bin/rspec') %>
  gemfile                   : ./test/integration/Gemfile

provisioner                 :
    name                    : ansible_push
    ansible_config          : "tests/ansible.cfg"
    chef_bootstrap_url      : nil
    use_instance_name       : True
    idempotency_test        : True
    diff                    : True
    sudo                    : True
    extra_vars               : "@./test/integration/simple/concourse-vars.yml"
    #verbose                 : "vvvvv"

platforms                   :
### Ubuntu 1404
 - name                     : "ubuntu1404_25"
   driver_config            :
     image                  : ubuntu:14.04
     platform               : ubuntu
   provisioner              :
      ansible_playbook_bin  : "`avm path v2.5`ansible-playbook"
      groups                :
         concourse-web      :
                              - 'simple-ubuntu1404-25'
         concourse-worker   :
                              - 'simple-ubuntu1404-25'
                              - 'worker-ubuntu1404-25'

 - name                     : "ubuntu1404_27"
   driver_config            :
     image                  : ubuntu:14.04
     platform               : ubuntu
   provisioner              :
      ansible_playbook_bin  : "`avm path v2.7`ansible-playbook"
      groups                :
         concourse-web      :
                              - 'simple-ubuntu1404-27'
         concourse-worker   :
                              - 'simple-ubuntu1404-27'
                              - 'worker-ubuntu1404-27'
### Ubuntu 1604
 - name                     : "ubuntu1604_25"
   driver_config            :
     image                  : ubuntu:16.04
     platform               : ubuntu
   provisioner              :
      ansible_playbook_bin  : "`avm path v2.5`ansible-playbook"
      groups                :
         concourse-web      :
                              - 'simple-ubuntu1604-25'
         concourse-worker   :
                              - 'simple-ubuntu1604-25'
                              - 'worker-ubuntu1604-25'

 - name                     : "ubuntu1604_26"
   driver_config            :
     image                  : ubuntu:16.04
     platform               : ubuntu
   provisioner              :
      ansible_playbook_bin  : "`avm path v2.6`ansible-playbook"
      groups                :
         concourse-web      :
                              - 'simple-ubuntu1604-26'
         concourse-worker   :
                              - 'simple-ubuntu1604-26'
                              - 'worker-ubuntu1604-26'

 - name                     : "ubuntu1604_27"
   driver_config            :
     image                  : ubuntu:16.04
     platform               : ubuntu
   provisioner              :
      ansible_playbook_bin  : "`avm path v2.7`ansible-playbook"
      groups                :
         concourse-web      :
                              - 'simple-ubuntu1604-27'
         concourse-worker   :
                              - 'simple-ubuntu1604-27'
                              - 'worker-ubuntu1604-27'
### Ubuntu 1804
 - name                     : "ubuntu1804_25"
   driver_config            :
     image                  : ubuntu:18.04
     platform               : ubuntu
   provisioner              :
      ansible_playbook_bin  : "`avm path v2.5`ansible-playbook"
      groups                :
         concourse-web      :
                              - 'simple-ubuntu1804-25'
         concourse-worker   :
                              - 'simple-ubuntu1804-25'
                              - 'worker-ubuntu1804-25'

 - name                     : "ubuntu1804_27"
   driver_config            :
     image                  : ubuntu:18.04
     platform               : ubuntu
   provisioner              :
      ansible_playbook_bin  : "`avm path v2.7`ansible-playbook"
      groups                :
         concourse-web      :
                              - 'simple-ubuntu1804-27'
         concourse-worker   :
                              - 'simple-ubuntu1804-27'
                              - 'worker-ubuntu1804-27'

suites:
  - name                    : simple
    provisioner             :
      playbook              : "test/integration/simple/simple.yml"
    driver_config           :
      hostname              : "simple"
