---

driver                      :
    name                    : docker
    socket                  : unix:///var/run/docker.sock
    use_sudo                : false
    privileged              : true
    volume                  : /opt/concourseci/worker
    provision_command       : mkdir -p /run/sshd

verifier                    :
  name                      : serverspec
  remote_exec               : false
  default_pattern           : true
  bundler_path              : <%= '/opt/hellofresh/kitchen/embedded/bin' if File.exist?('/opt/hellofresh/kitchen/embedded/bin/bundler') %>
  rspec_path                : <%= '/opt/hellofresh/kitchen/embedded/bin' if File.exist?('/opt/hellofresh/kitchen/embedded/bin/rspec') %>
  gemfile                   : ./test/integration/Gemfile

provisioner                 :
    name                    : ansible_push
    ansible_config          : "tests/ansible.cfg"
    chef_bootstrap_url      : nil
    use_instance_name       : True
    idempotency_test        : True
    diff                    : True
    sudo                    : True
    extra_vars              : "@./test/integration/simple/concourse-vars.yml"
    # verbose                 : "vvvvv"

platforms                   :
### Ubuntu 1404
 - name                     : "ubuntu1404_one"
   driver_config            :
     image                  : ubuntu:14.04
     platform               : ubuntu
   provisioner              :
      ansible_playbook_bin  : "`avm path vOne `ansible-playbook"
      groups                :
         concourse-web      :
                              - 'simple-ubuntu1404-one'
         concourse-worker   :
                              - 'simple-ubuntu1404-one'
                              - 'worker-ubuntu1404-one'

 - name                     : "ubuntu1404_three"
   driver_config            :
     image                  : ubuntu:14.04
     platform               : ubuntu
   provisioner              :
      ansible_playbook_bin  : "`avm path vThree `ansible-playbook"
      groups                :
         concourse-web      :
                              - 'simple-ubuntu1404-three'
         concourse-worker   :
                              - 'simple-ubuntu1404-three'
                              - 'worker-ubuntu1404-three'
### Ubuntu 1604
 - name                     : "ubuntu1604_one"
   driver_config            :
     image                  : ubuntu:16.04
     platform               : ubuntu
   provisioner              :
      ansible_playbook_bin  : "`avm path vOne `ansible-playbook"
      groups                :
         concourse-web      :
                              - 'simple-ubuntu1604-one'
         concourse-worker   :
                              - 'simple-ubuntu1604-one'
                              - 'worker-ubuntu1604-one'

 - name                     : "ubuntu1604_two"
   driver_config            :
     image                  : ubuntu:16.04
     platform               : ubuntu
   provisioner              :
      ansible_playbook_bin  : "`avm path vTwo `ansible-playbook"
      groups                :
         concourse-web      :
                              - 'simple-ubuntu1604-two'
         concourse-worker   :
                              - 'simple-ubuntu1604-two'
                              - 'worker-ubuntu1604-two'

 - name                     : "ubuntu1604_three"
   driver_config            :
     image                  : ubuntu:16.04
     platform               : ubuntu
   provisioner              :
      ansible_playbook_bin  : "`avm path vThree `ansible-playbook"
      groups                :
         concourse-web      :
                              - 'simple-ubuntu1604-three'
         concourse-worker   :
                              - 'simple-ubuntu1604-three'
                              - 'worker-ubuntu1604-three'
### Ubuntu 1804
 - name                     : "ubuntu1804_one"
   driver_config            :
     image                  : ubuntu:18.04
     platform               : ubuntu
   provisioner              :
      ansible_playbook_bin  : "`avm path vOne `ansible-playbook"
      groups                :
         concourse-web      :
                              - 'simple-ubuntu1804-one'
         concourse-worker   :
                              - 'simple-ubuntu1804-one'
                              - 'worker-ubuntu1804-one'

 - name                     : "ubuntu1804_three"
   driver_config            :
     image                  : ubuntu:18.04
     platform               : ubuntu
   provisioner              :
      ansible_playbook_bin  : "`avm path vThree `ansible-playbook"
      groups                :
         concourse-web      :
                              - 'simple-ubuntu1804-three'
         concourse-worker   :
                              - 'simple-ubuntu1804-three'
                              - 'worker-ubuntu1804-three'

suites:
  - name                    : simple
    provisioner             :
      playbook              : "test/integration/simple/simple.yml"
    driver_config           :
      hostname              : "simple"
