---
driver                      :
    name                    : docker
    socket                  : unix:///var/run/docker.sock
    use_sudo                : false
    privileged              : true

verifier                    :
  name                      : serverspec
  remote_exec               : false
  default_pattern           : true
  bundler_path              : <%= '/opt/hellofresh/kitchen/embedded/bin' if File.exist?('/opt/hellofresh/kitchen/embedded/bin/bundler') %>
  rspec_path                : <%= '/opt/hellofresh/kitchen/embedded/bin' if File.exist?('/opt/hellofresh/kitchen/embedded/bin/rspec') %>
  gemfile                   : ./test/integration/Gemfile

provisioner                 :
    name                    : ansible_push
    ansible_config          : "tests/ansible.cfg"
    chef_bootstrap_url      : nil
    use_instance_name       : True
    idempotency_test        : True
    diff                    : True
    sudo                    : True
    #extra_vars                : "@kitchen_vars.yml"
    verbose                 : "vvvv"

platforms                   :
 - name                     : "ubuntu1404_20"
   driver_config            :
     image                  : ubuntu:14.04
     platform               : ubuntu
     forward:
        - 8080:8080
   provisioner              :
      ansible_playbook_bin  : "`avm path v2.0`ansible-playbook"
      # Hash of other groups
      groups                :
         concourse-web      : [ 'simple-ubuntu1404' ]
         concourse-worker   : [ 'simple-ubuntu1404', 'worker-ubuntu1404' ]

 - name                     : "ubuntu1604_22"
   driver_config            :
     image                  : ubuntu:16.04
     platform               : ubuntu
   provisioner              :
      ansible_playbook_bin  : "`avm path v2.2`ansible-playbook"
      # Hash of other groups
      groups                :
         concourse-web      : [ 'simple-ubuntu1604' ]
         concourse-worker   : [ 'simple-ubuntu1604', 'worker-ubuntu1604' ]

 - name                     : "ubuntu1604_23"
   driver_config            :
     image                  : ubuntu:16.04
     platform               : ubuntu
   provisioner              :
      ansible_playbook_bin  : "`avm path v2.3`ansible-playbook"
      # Hash of other groups
      groups                :
         concourse-web      : [ 'simple-ubuntu1604' ]
         concourse-worker   : [ 'simple-ubuntu1604', 'worker-ubuntu1604' ]

suites:
  - name                    : simple
    provisioner             :
      playbook              : "test/integration/simple/simple.yml"
    driver_config           :
      hostname              : "simple"

  - name                    : manage
    provisioner             :
      playbook              : "test/integration/manage/manage.yml"
    driver_config           :
      hostname              : "manage"