---
# TRAVIS: local
# NO TRAVIS: vagrant
driver                      :
    name                    : docker
    socket                  : unix:///var/run/docker.sock
    use_sudo                : false
    publish_all             : true
    privileged              : true
    forward:
      - 8080:8080
  
verifier                    :
  name                      : serverspec
  remote_exec               : false
  default_pattern           : true
  
provisioner                 :  
    name                    : ansible_push
    ansible_config          : "tests/ansible.cfg"
    chef_bootstrap_url      : nil
    use_instance_name       : True
    idempotency_test        : True
    diff                    : True
    sudo                    : True
    #extra_vars                : "@kitchen_vars.yml"
    verbose                 : "vvvv"


platforms                   :
 - name                     : "ubuntu1404"
   driver_config            :
     image                  : ubuntu:14.04
     platform               : ubuntu
   provisioner              :
      ansible_playbook_bin  : "`avm path v2`ansible-playbook"
      # Hash of other groups
      groups                : 
         concourse-web      : [ 'simple-ubuntu1404' ]
         concourse-worker   : [ 'simple-ubuntu1404', 'worker-ubuntu1404' ]

 - name                     : "ubuntu1604"
   driver_config            :
     image                  : ubuntu:16.04
     platform               : ubuntu
   provisioner              :
      ansible_playbook_bin  : "`avm path v2`ansible-playbook"
      # Hash of other groups
      groups                : 
         concourse-web      : [ 'simple-ubuntu1604' ]
         concourse-worker   : [ 'simple-ubuntu1604', 'worker-ubuntu1604' ]

suites:
  - name                    : simple
    provisioner             :
      playbook              : "tests/simple/simple.yml"
    driver_config           :
      hostname              : "simple"
      network:
        - ["private_network", {ip: "192.168.50.150"}]
  # - name                    : worker
  #   provisioner             :
  #     playbook              : "tests/worker/worker.yml"
  #   driver_config           :
  #     hostname              : "worker"
  #     network           :
  #       - ["private_network", {ip: "192.168.50.151"}]
