# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby
trigger:
  - master
  - pr

jobs:
- job: main
  strategy:
   matrix:
    u14-A:
      KITCHEN_COMMAND: bundle exec kitchen test simple-ubuntu1404-one
      KITCHEN_ANSIBLE: one
    u14-B:
      KITCHEN_COMMAND: "bundle exec kitchen test simple-ubuntu1404-three"
      KITCHEN_ANSIBLE: three
    u16-A:
      KITCHEN_COMMAND: "bundle exec kitchen test simple-ubuntu1604-one"
      KITCHEN_ANSIBLE: one
    u16-B:
      KITCHEN_COMMAND: "bundle exec kitchen test simple-ubuntu1604-two"
      KITCHEN_ANSIBLE: two
    u16-C:
      KITCHEN_COMMAND: "bundle exec kitchen test simple-ubuntu1604-three"
      KITCHEN_ANSIBLE: three
    u18-A:
      KITCHEN_COMMAND: "bundle exec kitchen test simple-ubuntu1804-one"
      KITCHEN_ANSIBLE: one
    u18-B:
      KITCHEN_COMMAND: bundle exec kitchen test simple-ubuntu1804-three
      KITCHEN_ANSIBLE: three
    cluster:
      KITCHEN_COMMAND: ./test/test-cluster.sh
      KITCHEN_ANSIBLE: three

  pool:
    vmImage: 'ubuntu-latest'
  
  steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '>= 2.5'

  - script: |
            # Make sure everything's up to date.
            sudo apt-get update -qq
            sudo apt-get install -qq python-apt python-pycurl git python-pip ruby ruby-dev build-essential autoconf
            gem install bundler
            # sudo locale-gen en_US.UTF-8
            # sudo dpkg-reconfigure locales
    displayName: 'apt packages &  bundle install'

  - script: |
            bash ./test/ansible-setup.sh "${KITCHEN_ANSIBLE}"
            bash ./test/setup_roles.sh
    displayName: 'Ansible & helper role setup'

  - script: |
            bundle install
    displayName: 'Bundle install'

  - script: |  
            CURRENT_DIR="$(pwd)"
            cd ..
            ln -s "${CURRENT_DIR}" ansible-concourse
            cd ansible-concourse
            LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 ${KITCHEN_COMMAND}
    displayName: 'Run kitchen test'
