# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby
trigger:
  - master
  - pr

jobs:
- job: main
  strategy:
   matrix:
    # one:
    #   MyEnv: u14

    # two:
    #   MYENV: u16
    d:
      NAME: simple ubuntu 1804 (ansible three)
      INSTANCE: simple-ubuntu1804-three
      TEST_COMMAND: bundle exec kitchen test simple-ubuntu1804-three
      
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '>= 2.5'
  - script: printenv
    displayName: list
     
  - script: |
            # Make sure everything's up to date.
            sudo apt-get update -qq
            sudo apt-get install -qq python-apt python-pycurl git python-pip ruby ruby-dev build-essential autoconf
            gem install bundler
            # sudo locale-gen en_US.UTF-8
            # sudo dpkg-reconfigure locales
    displayName: 'apt packages &  bundle install'
  - script: |
            bash ./test/ansible-setup.sh
            bash ./test/setup_roles.sh
    displayName: 'Ansible & helper role setup'
  - script: |
            bundle install
    displayName: 'Bundle install'
  - script: |  
            CURRENT_DIR="$(pwd)"
            cd ..
            ln -s "${CURRENT_DIR}" ansible-concourse
            cd ansible-concourse
            LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 ${TEST_COMMAND}
    displayName: 'Run kitchen for XXX'
    continueOnError: true

  - script: |  
            ls .kitchen
            bundle exec kitchen exec $INSTANCE -c "ps aux | grep concour | grep -v grep"
            echo "******** Netstatl"
            bundle exec kitchen exec $INSTANCE -c "sudo netstat -antlp"
            echo "******** WORKER LOG"
            bundle exec kitchen exec $INSTANCE -c "sudo cat /var/log/concourse/concourseci_worker.log"
            echo "******** WEB LOG"
            bundle exec kitchen exec $INSTANCE -c "sudo cat /var/log/concourse/concourseci_web.log"
    displayName: 'list errors'



- job: test
  dependsOn: main
  condition: failed() # this job will only run if Foo fails
  steps:
  - script: |  
            CURRENT_DIR="$(pwd)"
            cd ..
            ln -s "${CURRENT_DIR}" ansible-concourse
            cd ansible-concourse
            ls .kitchen
            bundle exec kitchen exec $INSTANCE -c "ps aux | grep concour | grep -v grep"
            echo "I was triggred"
    displayName: 'list errors'