---

- name: auth | Install httpasswd
  apt:
    name: "python-passlib,python-bcrypt"
    state: "present"
  when: ansible_os_family == 'Debian' 

- name: auth | Check that one local user is added
  fail: 
    msg="At least one local user is needed"
  when: concourse_local_users | length == 0

- name: auth | Create bcrypt password for local users
  htpasswd:
    path: "{{ concourseci_base_dir }}/concourse_users"
    name: "{{ item.user }}"
    password: "{{ item.pass }}"
    crypt_scheme: "bcrypt"
    owner: root
    mode: 0640
  with_items: "{{ concourse_local_users }}"
  loop_control:
    label: "{{ item.user }}"

- name: auth | Get bcrypt passwords
  shell: "cat {{ concourseci_base_dir }}/concourse_users"
  changed_when: false
  register: list_users

- name: auth | Add concourse_add_local_user
  set_fact:
    concourse_facts_local_users:
      CONCOURSE_ADD_LOCAL_USER: "{{ list_users.stdout_lines  | join(',') }}"

- name: auth | Set empty dict concourse_facts_main_users
  set_fact:
    concourse_facts_main_users: {}

- name: auth | Add all local users to concourse main team if CONCOURSE_MAIN_TEAM_LOCAL_USER is not defined
  set_fact:
    concourse_facts_main_users:
      CONCOURSE_MAIN_TEAM_LOCAL_USER: "{% for local_user in concourse_local_users %}{{local_user.user}}{% if not loop.last %},{% endif %}{% endfor %}"
  when: concourse_web_options['CONCOURSE_MAIN_TEAM_LOCAL_USER'] is not defined

