---

- name: Install | Check Concourse archive stat
  stat:
    path: "{{ concourseci_bin_dir }}/{{ concourseci_binary_file }}"
  register: concourseci_binary_file_stat

- name: Install | Download Concourse CI
  get_url:
    url: "{{ concourseci_download_url }}"
    dest: "{{ concourseci_bin_dir }}/{{ concourseci_binary_file }}"
    timeout: 200
    mode: 0755
    tmp_dest: "{{ concourseci_bin_dir }}"
    validate_certs: false
  become_user: "{{ concourseci_user }}"
  register: concourseci_get
  when: concourseci_binary_file_stat.stat.exists == False
  notify:
   - restart concourse-worker
   - restart concourse-web

- name: Install | Concourse link binary
  file:
    src: "{{ concourseci_bin_dir }}/{{ concourseci_binary_file }}"
    dest: "{{ concourseci_bin_dir }}/concourse"
    state: "link"
  notify:
   - restart concourse-worker
   - restart concourse-web

- name: Install | Allow Concourse to bind to privileged ports
  capabilities:
    path: "{{ concourseci_bin_dir }}/{{ concourseci_binary_file }}"
    capability: cap_net_bind_service+ep
    state: present
  ignore_errors: true
