---

- name: kernel update | Install latest kernel
  apt: 
    name="linux-generic-lts-vivid"
    state=present
  register: kernel_update

- name: kernel update | Reboot now
  command: shutdown -r now
  when: kernel_update | changed and concourseci_reboot

- name: kernel update | Wait for ssh port to open again
  wait_for:
    port="{{ apt_port | default('22') }}"
    host="{{ apt_hostname | default(inventory_hostname) }}"
    delay=30
    timeout=180
    search_regex=OpenSSH
  connection: local
  become: False
  when: kernel_update | changed and concourseci_reboot

- name: kernel update | pause a little to ensure everything is running
  pause:
    seconds="5"
  when: kernel_update | changed and concourseci_reboot
