---

- name: manage | main | Download fly
  get_url:
     url: "{{ concourseci_manage_url }}/api/v1/cli?arch=amd64&platform={{ ansible_system | lower }}"
     dest: "{{ concourseci_bin_dir }}/fly"
     mode: 0755

- include: teams.yml